name: Asher Davitadi
favicon: null
layout_spectrum: 0.63562
typography_spectrum: 0.658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22b14c'
    - '#3f51b5'
    - '#7092be'
    - '#ffffff'
    - '#b5e61d'
  brandStrength: 1
  lightness: 0.858684521401301
  saturation: 1
  rhythmicContrast: 0.09717153059318662
purpose: []
