name: Asher Davitadi
favicon: null
layout_spectrum: 0.63562
typography_spectrum: 0.658
title: Asher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00695c'
    - '#009587'
    - '#4db6ac'
    - '#9fc6c1'
  brandStrength: 1
  lightness: 0.858684521401301
  saturation: 1
  rhythmicContrast: 0.09717153059318662
purpose: []
