name: Asher Davitadi
favicon: null
layout_spectrum: 0.38473573653027415
typography_spectrum: 0.658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4921619517263025
  lightness: 0.858684521401301
  saturation: 0.011312402784824371
  rhythmicContrast: 0.09717153059318662
purpose: []
